import type { Metadata } from 'next'
import './styles/globals.css'
import { Header } from '@/widgets/Header/Header'
import { Contact } from '@/widgets/Contact/Contact'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body>
        <Header />
        <main>
          {children}
          <Contact />
        </main>
      </body>
    </html>
  )
}
